version: "0.2"
ignorePaths:
  - .vscode/
  - .devcontainer/
words:
  - devcontainer
  - fastapi
  - nullable
  - PGDB
  - PGHOST
  - PGPORT
  - PGUSER
  - postgresql
  - psycopg
  - pydantic
  - pyproject
  - sqlalchemy
  - unicode
  - uvicorn
  - varchar
  - venv
