[tool.poetry]
name = "bookstore"
version = "0.1.0"
description = ""
authors = ["Maksuel Nascimento <mk-nascimento@hotmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.11.*"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
